export const S3_FILE_CONTENT_MD5_TAG = "MD5";
export const S3_FILE_CONTENT_SCAN_START_TAG = "SCAN_START";
export const S3_FILE_CONTENT_SCAN_END_TAG = "SCAN_END";
export const S3_FILE_CONTENT_SCAN_IS_INFECTED_TAG = "SCAN_IS_INFECTED";
